language: python
dist: xenial

python:
    - "3.8"

install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"

script:
    - flake8 src
    - "./run_tests"

after_success:
    coveralls --data_file src/.coverage
